typography_spectrum: 1
color:
  brandColors:
    - '#B6B8C4'
    - '#7F7269'
    - '#183314'
    - '#DDD8D5'
    - '#F4FFFE'
  brandStrength: 0.990132
  lightness: 1
  rhythmicContrast: 0.495066
  saturation: 0.507401
layout_spectrum: 0.898026
author:
  email: DeepSouthMS3@gmail.com
  name: Heath Patterson
  url: HeathPatterson.net
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9fee31ee-5f57-4f08-b35f-4113604e57bc.jpg
name: DeepSouthMS3
title: Live Social Streamer
